<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'Thêm danh  mục';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class="row">
 <div class="col-lg-6">
 <?php
 $form->setAttribute('action', $this->url('danh_muc/crud', array('action' => 'add')));
 $form->setAttribute('role','form');
 //$form->setAttribute('class','form-inline');
 $form->prepare();

 echo $this->form()->openTag($form);
 echo '<br>'; 
 echo $this->formHidden($form->get('id'));// lấy element ra sử dụng phương thức get()
 echo '<br>'; 
 ?>
 <div class="form-group"> 	
 		<?php $ten=$form->get('ten');?>
 		<?php $ten->setAttribute('class','form-control');?>
 		<label><?php echo $ten->getLabel(); ?></label>
 		<?php echo $this->formElement($ten);?> 
</div>


<div class="form-group">
	<?php $moTa=$form->get('moTa'); ?>
	<?php $moTa->setAttribute('class','form-control');?>
	<label><?php echo $moTa->getLabel(); ?></label>
	<?php echo $this->formElement($moTa);?>
</div>




<div class="form-group">
	<?php $cha=$form->get('cha'); ?>
	<?php $cha->setAttribute('class','form-control')?>
	<label><?php echo $cha->getLabel(); ?></label>
	<?php echo $this->formElement($cha);?>
</div>

	<?php 
	$submit=$form->get('submit'); 
	$submit->setValue('Thêm danh mục');
	echo $this->formSubmit($submit);
	echo $this->form()->closeTag();
 	?>

 </div>
 </div>